apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mini-twitter
  labels:
    app.kubernetes.io/name: mini-twitter-backend
    app.kubernetes.io/part-of: mini-twitter
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/minitwitter"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "60000ms"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_VIRTUAL_HOST: "/"
  JWT_EXPIRATION: "86400000"
  SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: "0"
