apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mini-twitter
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mini-twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: mini-twitter
      annotations:
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          args: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
