apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mini-twitter
  labels:
    app.kubernetes.io/name: mini-twitter-frontend
    app.kubernetes.io/part-of: mini-twitter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: mini-twitter-frontend
