# Copy to rabbitmq-secret.yaml or use kubectl create secret.
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mini-twitter
type: Opaque
stringData:
  username: guest
  password: CHANGEME_RABBIT_PASSWORD
